import Head from 'next/head'
import { Inter } from '@next/font/google'
import axios from 'axios'
import Home from '../components/home/Home'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'],  })

export default function Index({categoryList, productList}) {
  /* const [productList, setProductList] = useState([])
  const [categoryList, setCategoryList] = useState([])

  useEffect(() => {
    const getAll = async () => {
      const category = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`)
      setCategoryList(category.data)
      const product = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`)
      setProductList(product.data)
    }
    getAll()
  }, []) */
  

  return (
    <>
      <Head>
        <title>Yemek Sipariş</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Home productList={productList} categoryList={categoryList}/>
    </>
  )
}

export async function getServerSideProps() {

  const category = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`)
  const product = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`)

  return {
    props: {
      categoryList: category.data ? category.data : [],
      productList: product.data ? product.data : []
    }
  }
}